### ISSUE TITLE
Age Moments Report error when the difference is negetive

### ISSUE THREAD

**Issue by AtelierAmber** [divineDerivative/WayBetterRomance#6]
![image](https://github.com/divineDerivative/WayBetterRomance/assets/22966571/5c0365cd-1315-4344-9754-1c12c654ea6c)

The Modulo operator is returning -1 when performing the difference calculation. This causes it to error out. You can see with the Paniel Race it luckily is divisible by 3 so it returns 0 and still generates... "Acceptable" (? Honestly, don't even ask me why the ages are all fucked up). The error wouldn't be too big of a deal if it didn't quit out of the moments function.

Solution would be to either completely redo the moments function to account for weird ages like this or to just simply absolute value the difference and ignore the weird ages.

**Comment by divineDerivative** [comment]
Nah, they just need to be recognized as robots. I’m out of town right now but can fix it tomorrow. In the meantime you can add `<growthAges />` to the `generalSettings` section of their racedef. Null growth moments will be automatically recognized as robots.
